---
language: c

before_install:
  # Travis runs a detached head. We need to find the current branch
  - git checkout `git branch --contains HEAD | grep -v '*'`
  # Also tags for the root(s) of the minor version(s)
  - git fetch origin --tags
  - mkdir ~/bin
install:
before_script:
  # arduino requires an X server even with command line
  # https://github.com/arduino/Arduino/issues/1981
  - Xvfb :1 -screen 0 1024x768x16 &> xvfb.log &
  # change back to home directory for compiling
  - cd $TRAVIS_BUILD_DIR
script:
  # build default config
  - echo "Tests Suppressed"
